### ISSUE TITLE
iScroll doesn't work in chrome dev device mode

### ISSUE THREAD

**Issue by GeorgioWan** [GeorgioWan/react-ocard#2]
When using Chrome dev tool, iScroll can't scroll!!

Currently, we use this way to solve this problem: 

```jsx
const options = {
    disablePointer: true,
    disableTouch:  false,
    disableMouse: true
}
```
> **Ref:** https://github.com/cubiq/iscroll/issues/1109

**Comment by korgong** [comment]
you save my time!!!

**Comment by GeorgioWan** [comment]
@korgong NICE!!!!!!!!! 🎉
